export const userType = {
  CREATE_USER: 'CREATE_USER',
  GET_ALL_USERS: 'GET_ALL_USERS',
  GET_USER_BY_ID: 'GET_USER_BY_ID',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  RESET_PASSWORD: 'RESET_PASSWORD',
  RESET_NEW_PASSWORD: 'RESET_NEW_PASSWORD',
  UPDATE_AVATAR: 'UPDATE_AVATAR',
  SEARCH_USER: 'SEARCH_USER',
  CLEAR_SEARCH_USERS: 'CLEAR_SEARCH_USERS',
};
