export const userType = {
  CREATE_USER: 'CREATE_USER',
  PAGINATE_USERS: 'PAGINATE_USERS',
  GET_USER_BY_ID: 'GET_USER_BY_ID',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  RESET_PASSWORD: 'RESET_PASSWORD',
  RESET_NEW_PASSWORD: 'RESET_NEW_PASSWORD',
  UPDATE_AVATAR: 'UPDATE_AVATAR',
  SEARCH_USERS: 'SEARCH_USERS',
  CLEAR_SEARCH_USERSS: 'CLEAR_SEARCH_USERSS',
};
