export const tagType = {
  GET_PAGINATION_TAGS: 'GET_PAGINATION_TAGS',
  GET_TAGS: 'GET_TAGS',
  CREATE_TAG: 'CREATE_TAG',
  GET_TAG: 'GET_TAG',
  UPDATE_TAG: 'UPDATE_TAG',
  DELETE_TAG: 'DELETE_TAG',
};
