export const answerType = {
  PAGINATE_ANSWERS: 'PAGINATE_ANSWERS',
  GET_USERS_LIKE_BY_ANSWER_ID: 'GET_USERS_LIKE_BY_ANSWER_ID',
  GET_ANSWER_BY_ID: 'GET_ANSWER_BY_ID',
  CREATE_ANSWER: 'CREATE_ANSWER',
  UPDATE_ANSWER: 'UPDATE_ANSWER',
  DELETE_ANSWER: 'DELETE_ANSWER',
  LIKE_UNLIKE_ANSWER: 'LIKE_UNLIKE_ANSWER',
  CHOOSE_QUESTION: 'CHOOSE_QUESTION',
  CLEAR_CURRENT_QUESTION: 'CLEAR_CURRENT_QUESTION',
  CHOOSE_USER: 'CHOOSE_USER',
  CLEAR_CURRENT_USER: 'CLEAR_CURRENT_USER',
};
