export const answerType = {
  CREATE_ANSWER: 'CREATE_ANSWER',
  GET_ALL_ANSWERS: 'GET_ALL_ANSWERS',
  GET_ANSWER: 'GET_ANSWER',
  PAGINATE_ANSWERS: 'PAGINATE_ANSWERS',
  UPDATE_ANSWER: 'UPDATE_ANSWER',
  DELETE_ANSWER: 'DELETE_ANSWER',
  LIKE_UNLIKE_ANSWER: 'LIKE_UNLIKE_ANSWER',
  CHOOSE_QUESTION: 'CHOOSE_QUESTION',
  CLEAR_CURRENT_QUESTION: 'CLEAR_CURRENT_QUESTION',
  CHOOSE_USER: 'CHOOSE_USER',
  CLEAR_CURRENT_USER: 'CLEAR_CURRENT_USER',
};
