export const questionType = {
  CREATE_QUESTION: 'CREATE_QUESTION',
  GET_ALL_QUESTIONS: 'GET_ALL_QUESTIONS',
  GET_QUESTION_BY_ID: 'GET_QUESTION_BY_ID',
  UPDATE_QUESTION: 'UPDATE_QUESTION',
  DELETE_QUESTION: 'DELETE_QUESTION',
};
