export const questionType = {
  CREATE_QUESTION: 'CREATE_QUESTION',
  PAGINATE_QUESTIONS: 'PAGINATE_QUESTIONS',
  GET_QUESTION_BY_ID: 'GET_QUESTION_BY_ID',
  UPDATE_QUESTION: 'UPDATE_QUESTION',
  DELETE_QUESTION: 'DELETE_QUESTION',
  SEARCH_QUESTIONS: 'SEARCH_QUESTIONS',
  CLEAR_SEARCH_QUESTIONS: 'CLEAR_SEARCH_QUESTIONS',
  CHOOSE_USER: 'CHOOSE_USER',
  CLEAR_CURRENT_USER: 'CLEAR_CURRENT_USER',
};
